services:
  php:
    container_name: php
    build:
      context: docker/php
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: 'serverName=webSite'
    volumes:
      - ./:/var/www/web
  nginx:
    container_name: nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/web:cached
    ports:
      - ${NGINX_PORT:-80}:80
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    volumes:
      - ./docker/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT:-3306}:3306

